// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DocumentsList: typeof import('./components/DocumentsList.vue')['default']
    EmailModal: typeof import('./components/EmailModal.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
